### ISSUE TITLE
Build error "window is not defined" with node v10

### ISSUE THREAD

**Issue by Fi1osof** [fullcalendar/fullcalendar-react#134]
### Bug Reports

After upgrade version.

```
> Build error occurred
{ ReferenceError: window is not defined
    at Object.<anonymous> (/www/freecode.academy/node_modules/@fullcalendar/react/dist/vdom.cjs.js:8:51)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/www/freecode.academy/node_modules/@fullcalendar/react/dist/main.cjs.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30) type: 'ReferenceError' }
error Command failed with exit code 1.
```

node-js v12 and v14 OK. 

CI: https://github.com/freecode-academy/freecode.academy/runs/2266854359?check_suite_focus=true

**Comment by arshaw** [comment]
Making the decision to have minimum of Node 14.

The v6 codebase now uses pnpm, which ensures the pinned version of Node.
