### ISSUE TITLE
Not available in fullcalendar/core version 4.4.2

### ISSUE THREAD

**Issue by lovelesh-nagarro** [fullcalendar/fullcalendar-react#73]
Bug Reports
Issue that is https://github.com/fullcalendar/fullcalendar-react/issues/17, still coming in
fullcalendar/core version 4.4.2.

Getting below error while using fullcalendar with react
### Element is not defined
**ReferenceError: Element is not defined
    at C:\Users\loveleshkumar\Desktop\web_mclinic\node_modules\@fullcalendar\core\main.js:108:25**
    at C:\Users\loveleshkumar\Desktop\web_mclinic\node_modules\@fullcalendar\core\main.js:8:68
    at Object.<anonymous> (C:\Users\loveleshkumar\Desktop\web_mclinic\node_modules\@fullcalendar\core\main.js:11:2)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at C:\Users\loveleshkumar\Desktop\web_mclinic\node_modules\@fullcalendar\react\main.umd.js:7:103
    at Object.<anonymous> (C:\Users\loveleshkumar\Desktop\web_mclinic\node_modules\@fullcalendar\react\main.umd.js:10:2)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4784
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
